name: 02-create_release
on:
  push:
    tags:
      - 'v*.*.*-hotfix'
jobs:
   
  publish-image:
    permissions:
      id-token: write
      packages: write
      contents: read
    uses: ./.github/workflows/d-publish-image.yaml
    with:
      client: "image-release"
      image_name: "quay.io/${{ github.repository_owner }}/kubescape"
      image_tag: ${{ github.ref_name }}
      support_platforms: true
      cosign: false
    secrets: inherit
